import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	containerFirst: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: 'green',
	},
	container: {
		flex: 1,
		padding: 24,
		justifyContent: 'center',
		backgroundColor: 'grey',
	},	
	contentContainer: {
		flex: 1,
		alignItems: 'center',
	},
	lottie: {
		width: 300,
		height: 300
	},
	loginscreen: {
		flex: 1,
		fontFamily: 'Rubik-Medium',
		backgroundColor: "#EEF1FF",
		alignItems: "center",
		justifyContent: "center",
		padding: 12,
		width: "100%",
	},
	loginheading: {
		fontFamily: 'Rubik-Medium',
		fontSize: 26,
		marginBottom: 10,
	},
	logininputContainer: {
		fontFamily: 'Rubik-Medium',
		width: "100%",
		alignItems: "center",
		justifyContent: "center",
	},
	logininput: {
		fontFamily: 'Rubik-Medium',
		borderWidth: 1,
		width: "90%",
		padding: 8,
		borderRadius: 2,
	},
	loginbutton: {
		fontFamily: 'Rubik-Medium',
		backgroundColor: "green",
		padding: 12,
		marginVertical: 10,
		width: "60%",
		borderRadius: 50,
		elevation: 1,
	},
	loginbuttonText: {
		fontFamily: 'Rubik-Medium',
		textAlign: "center",
		color: "#fff",
		fontWeight: "600",
	},
	chatscreenScrollView: {
		fontFamily: 'Rubik-Medium',
		// backgroundColor: "#F7F7F7",
		backgroundColor: "#F7F7F7",
		flex: 1,
		paddingTop: 5,
		position: "relative",
		height: 700,
		// marginBottom:250,
	},
	chatscreen: {
		fontFamily: 'Rubik-Medium',
		// backgroundColor: "#F7F7F7",
		backgroundColor: "#F7F7F7",
		flex: 1,
		paddingTop: 20,
		padding: 5,
		position: "relative",
		height: 700,
		// marginBottom:250,
	},
	chatscreenModal: {
		fontFamily: 'Rubik-Medium',
		backgroundColor: "#F7F7F7",
		// flex: 1,
		// paddingTop: 20,
		padding: 5,
		position: "absolute",
		height: '50',
		bottom: 10,
		left: 0,
	},
	chatheading: {
		fontFamily: 'Rubik-Medium',
		fontSize: 24,
		fontWeight: "bold",
		color: "green",
	},
	chattopContainer: {
		fontFamily: 'Rubik-Medium',
		backgroundColor: "#F7F7F7",
		height: 70,
		width: "100%",
		padding: 20,
		justifyContent: "center",
		marginBottom: 15,
		elevation: 2,
	},
	chatheader: {
		fontFamily: 'Rubik-Medium',
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	chatlistContainer: {
		fontFamily: 'Rubik-Medium',
		paddingHorizontal: 10,
		height: '100%'
	},
	chatlistContainerView: {
		height: '100%',
		width: '100%',
	},
	chatemptyContainer: {
		fontFamily: 'Rubik-Medium',
		width: "100%",
		height: "80%",
		marginTop: 60,
		alignItems: "center",
		justifyContent: "center",
	},
	chatemptyText: {
		fontFamily: 'Rubik-Medium', fontWeight: "normal", fontSize: 20, paddingBottom: 30
	},
	messagingscreen: {
		fontFamily: 'Rubik-Medium',
		flex: 1,
	},
	messaginginputContainer: {
		fontFamily: 'Rubik-Medium',
		width: "100%",
		minHeight: 60,
		backgroundColor: "white",
		paddingVertical: 10,
		paddingHorizontal: 15,
		justifyContent: "center",
		flexDirection: "row",
	},
	messaginginput: {
		fontFamily: 'Rubik-Light',
		borderWidth: 1,
		borderColor: "#dfe1eb",
		padding: 15,
		flex: 1,
		marginRight: 10,
		borderRadius: 20,
	},
	messagingbuttonContainer: {
		fontFamily: 'Rubik-Medium',
		width: "17%",
		height: 55,
		// backgroundColor: "green",
		backgroundColor: "#25D366",
		borderRadius: 3,
		textAlign: "center",
		alignItems: "center",
		justifyContent: "center",
		borderRadius: 50,
	},
	messagingbuttonContainerPressed: {
		fontFamily: 'Rubik-Medium',
		width: "17%",
		height: 55,
		// backgroundColor: "green",
		backgroundColor: "#32a852",
		borderRadius: 3,
		textAlign: "center",
		alignItems: "center",
		justifyContent: "center",
		borderRadius: 50,
	},
	modalbutton: {
		fontFamily: 'Rubik-Medium',
		width: "40%",
		height: 45,
		backgroundColor: "green",
		borderRadius: 5,
		alignItems: "center",
		justifyContent: "center",
		color: "#fff",
	},
	modalbuttonContainer: {
		fontFamily: 'Rubik-Medium',
		flexDirection: "row",
		justifyContent: "space-between",
		marginTop: 10,
	},
	modaltext: {
		fontFamily: 'Rubik-Medium',
		color: "#fff",
	},
	modalDoctor: {
		flex: 1,
		fontFamily: 'Rubik-Medium',
		width: "100%",
		// borderTopColor: "#ddd",
		// borderTopWidth: 0,
		// borderRadius:25,
		// elevation: 1,
		marginTop: 100,
		marginRight: 0,
		height: "100%",
		backgroundColor: "#000",
		// position: "absolute",
		bottom: 0,
		// right:10,
		// zIndex: 10,		
		// paddingVertical: 10,
		// paddingHorizontal: 20,
	},
	modalContainer: {
		fontFamily: 'Rubik-Medium',
		width: "100%",
		// borderTopColor: "#ddd",
		// borderTopWidth: 0,
		// borderRadius:25,
		// elevation: 1,
		marginRight: 0,
		height: "100%",
		// backgroundColor: "#fff",
		position: "absolute",
		bottom: 0,
		right: 10,
		zIndex: 10,
		paddingVertical: 10,
		paddingHorizontal: 20,
	},
	modalinput: {
		fontFamily: 'Rubik-Medium',
		borderWidth: 2,
		padding: 15,
	},
	modalsubheading: {
		fontFamily: 'Rubik-Medium',
		fontSize: 20,
		fontWeight: "bold",
		marginBottom: 15,
		textAlign: "center",
	},
	mmessageWrapper: {
		fontFamily: 'Rubik-Medium',
		width: "100%",
		alignItems: "flex-start",
		marginBottom: 15,
	},
	mmessage: {
		fontFamily: 'Rubik-Medium',
		maxWidth: "50%",
		backgroundColor: "#f5ccc2",
		padding: 10,
		borderRadius: 10,
		marginBottom: 2,
	},
	notshowusername: {
		fontFamily: 'Rubik-Medium',
		opacity: 0,
		height: 0,
		width: 0
	},
	mvatar: {
		fontFamily: 'Rubik-Medium',
		marginRight: 5,
	},
	cchat: {
		fontFamily: 'Rubik-Medium',
		width: "100%",
		flexDirection: "row",
		alignItems: "center",
		borderRadius: 5,
		paddingHorizontal: 15,
		backgroundColor: "#fff",
		height: 80,
		marginBottom: 10,
	},
	cchatoffline: {
		fontFamily: 'Rubik-Medium',
		width: "100%",
		flexDirection: "row",
		alignItems: "center",
		borderRadius: 5,
		paddingHorizontal: 15,
		backgroundColor: "#e6e6e6",
		height: 80,
		marginBottom: 10,
	},
	cavatar: {
		fontFamily: 'Rubik-Medium',
		marginRight: 15,
	},
	cavatarchat: {
		marginRight: 15,
		width: 50,
		height: 50,
		borderRadius: 150 / 2,
		overflow: "hidden"
	},
	cavatarchattop: {
		fontFamily: 'Rubik-Medium',
		marginRight: 15,
		width: 30,
		height: 30,
		borderRadius: 150 / 2,
		overflow: "hidden"
	},
	cbubble: {
		fontFamily: 'Rubik-Medium',
		marginRight: 25,
	},
	cusername: {
		fontFamily: 'Rubik-Light',
		fontSize: 14,
		marginBottom: 5,
		fontWeight: "bold",
	},
	cusername_newchat: {
		fontFamily: 'Rubik-ExtraBold',
		fontSize: 14,
		marginBottom: 5,
		fontWeight: "bold",
	},
	cmessage: {
		fontFamily: 'Rubik-Light',
		fontSize: 11,
		opacity: 0.7,
	},
	cmessage_newchat: {
		fontFamily: 'Rubik-ExtraBold',
		fontWeight: "bold",
		fontSize: 11,
		opacity: 0.7,
	},
	ctotal_newchat: {
		fontFamily: 'Rubik-ExtraBold',
		fontWeight: "bold",
		color: "#FFF",
		fontSize: 9,
		opacity: 0.7,
	},
	crightContainer: {
		fontFamily: 'Rubik-Medium',
		flexDirection: "row",
		justifyContent: "space-between",
		flex: 1,
	},
	ctime: {
		fontSize: 10,
		fontFamily: 'Rubik-Light',
		opacity: 0.5,
	},
	ctime_newchat: {
		fontSize: 10,
		fontFamily: 'Rubik-Light',
		fontWeight: "bold",
		opacity: 0.9,
	},
	modalHeader: {
		fontFamily: 'Rubik-Medium',
		marginBottom: 5,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	ccountlistchat: {
		fontFamily: 'Rubik-Medium',
		textAlign: "center",
	},
	ccloselistchat: {
		fontFamily: 'Rubik-Medium',
		textAlign: "right",
	},
	floatBtnChat: {
		fontFamily: 'Rubik-Medium',
		width: 70,
		height: 70,
		borderRadius: 30,
		backgroundColor: '#10dce3',
		position: 'absolute',
		margin: 'auto',
		alignItems: 'center',
		justifyContent: 'center',
		bottom: 10,
		right: 10,
	}
});
